.TH VAL-SUB-MANAGER 8 "2026-05-30" "versatile-autoreg-val" "System Administration"
.SH NAME
val-sub-manager \- Supervisor for VAL sub-instance daemons
.SH SYNOPSIS
.B val-sub-manager
.SH DESCRIPTION
.B val-sub-manager
scans
.I /etc/val/val.sub/
for sub-instance directories that contain both a
.I val.conf
file and a
.I .enabled
marker, then launches one
.BR val-sub (8)
process per discovered sub-instance.
.PP
It monitors child processes every 30 seconds and restarts any that have
died. An instance that exits repeatedly in less than
.B MIN_UPTIME_SECS
(30 s) seconds increments a failure counter; after
.B MAX_FAILS
(5) consecutive failures the sub-instance is marked dead and no longer
restarted.
.PP
.B val-sub-manager
protects against being started twice using a PID file at
.IR /var/lib/val/val-sub-manager.pid .
SIGTERM and SIGINT are propagated to all child processes.
.PP
It is normally launched automatically by
.BR val (8)
when
.B PARALLEL_MODE
is set to
.B both
or
.BR only_parallel .
.SH SEE ALSO
.BR val (8),
.BR val-sub (8),
.BR val-sub-instance (8)
.SH AUTHOR
Gabriel Navia <correos@gabrielnav.es>
